//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 mattzech.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExistingAWSResources) DeepCopyInto(out *ExistingAWSResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExistingAWSResources.
func (in *ExistingAWSResources) DeepCopy() *ExistingAWSResources {
	if in == nil {
		return nil
	}
	out := new(ExistingAWSResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkGenerator) DeepCopyInto(out *NetworkGenerator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkGenerator.
func (in *NetworkGenerator) DeepCopy() *NetworkGenerator {
	if in == nil {
		return nil
	}
	out := new(NetworkGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkGenerator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkGeneratorList) DeepCopyInto(out *NetworkGeneratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkGenerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkGeneratorList.
func (in *NetworkGeneratorList) DeepCopy() *NetworkGeneratorList {
	if in == nil {
		return nil
	}
	out := new(NetworkGeneratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkGeneratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkGeneratorSpec) DeepCopyInto(out *NetworkGeneratorSpec) {
	*out = *in
	if in.CIDRBlocks != nil {
		in, out := &in.CIDRBlocks, &out.CIDRBlocks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ExistingAWSResources != nil {
		in, out := &in.ExistingAWSResources, &out.ExistingAWSResources
		*out = make([]ExistingAWSResources, len(*in))
		copy(*out, *in)
	}
	if in.VPCEndpoints != nil {
		in, out := &in.VPCEndpoints, &out.VPCEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*v1alpha1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1alpha1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkGeneratorSpec.
func (in *NetworkGeneratorSpec) DeepCopy() *NetworkGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkGeneratorStatus) DeepCopyInto(out *NetworkGeneratorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkGeneratorStatus.
func (in *NetworkGeneratorStatus) DeepCopy() *NetworkGeneratorStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkGeneratorStatus)
	in.DeepCopyInto(out)
	return out
}
