# permissions for end users to view networkgenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: networkgenerator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: netgen-operator
    app.kubernetes.io/part-of: netgen-operator
    app.kubernetes.io/managed-by: kustomize
  name: networkgenerator-viewer-role
rules:
- apiGroups:
  - kosmos.matt.test.dev
  resources:
  - networkgenerators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kosmos.matt.test.dev
  resources:
  - networkgenerators/status
  verbs:
  - get
